# Generated by Django 4.2.6 on 2023-10-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='backend.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='backend.student')),
            ],
        ),
    ]
