# Generated by Django 4.2.6 on 2023-10-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_discipline'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discipline',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usertype',
            table=None,
        ),
    ]
