# Generated by Django 4.2.6 on 2023-10-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='backend.teacher'),
        ),
    ]
