# Generated by Django 4.2.6 on 2023-10-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_coordinator_table_alter_discipline_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Coordinator')], default=1),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
