# Generated by Django 4.2.6 on 2023-10-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user_auth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.IntegerField(choices=[(1, 'User'),(2, 'Student'),(3, 'Teacher'),(4, 'Coordinator'),(5, 'Discipline'),(6, 'Grade')], default=1)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['resource'],
                'unique_together': ('resource', 'can_read', 'can_write')
            }
        ),
    ]
